### ISSUE TITLE
Windows, Mac?

### ISSUE THREAD

**Issue by hollowdoor** [kemitchell/native-readdir-stream.js#1]
This won't work on windows, or mac will it?

Do you think I could use optional dependencies to change to regular readdir on those operating systems?

**Comment by DomVinyard** [comment]
My understanding was that this was a cross-platform solution? Could this be clarified please. Thanks

**Comment by hollowdoor** [comment]
This library uses the `native-readdir` module here https://github.com/kemitchell/native-readdir.js

`native-readdir` uses `dirent.h`. I was concerned because dirent has had problems on windows before at least. After some research I see that mac definitely can use it, but I have found conflicting information for windows. Perhaps I was hasty in posting this issue.

**Comment by DomVinyard** [comment]
@kemitchell Hello there! Would you be able to drop a brief comment on the portability of this module.

Thank you :)

**Comment by hollowdoor** [comment]
@DomVinyard There is a implementation for `dirent.h` for windows, but I doubt that's what is being used here. Also I think `dirent.h` for windows needs to be compiled with a windows c/c++ compiler to work.

Really I could care less about windows support, but this could be a valid concern in the future.

**Comment by DomVinyard** [comment]
I do very much need windows support, what would it take to get windows support here? I'm happy to contribute

**Comment by kemitchell** [comment]
@domvinyard: I honestly don't know what it would take. If you want to use what's here as a starting point for a Windows package, you're more than welcome.

**Comment by DomVinyard** [comment]
@kemitchell heya, appreciate your encouragement (and thank for all your work here!). Would you be able to point me in the direction of any resources to help me get started?
